title: Blip
description: "Sublime MySQL monitoring"
incremental: true
baseurl: /blip
twitter_username: cashapp
github_username: cashapp
markdown: kramdown
plugins:
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .jekyll-cache
  - serve.sh
  - build.sh

remote_theme: just-the-docs/just-the-docs
search_enabled: true
aux_links:
  "Blip":
    - "//github.com/cashapp/blip"

permalink: /:path/:name
toc:
  min_level: 1
  max_level: 3
